version: "3.9"
services:
  backend:
    image: ecos_annotator_server:latest
    container_name: ecos-annotator-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    entrypoint: 
      - bash 
      - -c 
    command: >
      "label-studio start"